version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  lint:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - run: go mod download
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0 
      - run: golangci-lint run --timeout 300s --issues-exit-code 0

  build:
    docker:
      - image: circleci/golang:1.15.8
    working_directory: /go/src/bakingbacon
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Build
          command: go build -v

orbs:
  go: circleci/go@1.7.0

# Invoke jobs via workflows
workflows:
  lint_only:
    jobs:
      - lint
