name: bacon-builder
on: push
env:
  WEBSERVER_PATH: ${{ github.workspace }}/webserver

jobs:
  linux-windows-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Setup Node/NPM
      uses: actions/setup-node@v1
      with:
        node-version: 14.15

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        key: bakinbacon-npm-${{ hashFiles('**/package-lock.json') }}
        path: "${{ env.WEBSERVER_PATH }}/node_modules"

    - name: Install node_modules
      working-directory: ${{ env.WEBSERVER_PATH }}
      run: npm install

    - name: Build web ui
      working-directory: ${{ env.WEBSERVER_PATH }}
      env:
        CI: "false"
      run: npm run build

    - name: Bellybutton lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        skip-go-installation: true

    - name: Fry some linux bacon
      run: make && make dist

    - name: Fry some windows bacon
      run: make windows && make windows-dist

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: |
          bakinbacon-linux-amd64.tar.gz
          bakinbacon-windows-amd64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
