name: bacon-builder
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Setup Node/NPM
      uses: actions/setup-node@v1
      with:
        node-version: 14.15

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        key: bakinbacon-npm-${{ hashFiles('**/package-lock.json') }}
        path: ${{ GITHUB_WORKSPACE }}/webserver/node_modules

    - name: Install node_modules
      working-directory: ${{ GITHUB_WORKSPACE }}/webserver
      run: npm install

    - name: Build web ui
      working-directory: ${{ GITHUB_WORKSPACE }}/webserver
      env:
        CI: "false"
      run: npm run build

    - name: Bellybutton lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        skip-go-installation: true

    - name: Fry some bacon
      run: go build .

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bakinbacon
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
